### PR TITLE
add more Hitbox to Ragebot

### PR DESCRIPTION
**Pull request by dapaster**
image

### CODE REVIEW

**Comment by codecheck01** [comment]
This is not what you want for a ragebot, look at other cheats.

**Comment by Navoichyk** [comment]
> This is not what you want for a ragebot, look at other cheats.

wdym by this? Because it makes a ton of sense to be able to be more specific to the hitboxes

**Comment by codecheck01** [comment]
I meant this pull request just add every hitbox possible to the GUI, this is not what you want.

**Comment by notgoodusename** [comment]
More isnt better

**Pull request closed without merging**
