### PR TITLE
Jitter Offset

### PR DESCRIPTION
**Pull request by JannesBonk**
Adds jitter for Anti-Aim ( note : this was pasted from old source )

### CODE REVIEW

**Review by gr1ndy — COMMENTED** [review]
just why...

**Comment by gr1ndy** [comment]
plus there already is jitter.

https://github.com/notgoodusename/OsirisAndExtra/blob/774067a5a0c5951e76d304226c39e65f8cbaa682/Osiris/GUI.cpp#L677-L697

and its good as it is

**Comment by JannesBonk** [comment]
> plus there already is jitter.
> 
> https://github.com/notgoodusename/OsirisAndExtra/blob/774067a5a0c5951e76d304226c39e65f8cbaa682/Osiris/GUI.cpp#L677-L697
> 
> and its good as it is

thats invert jitter bro not jitter yaw , it's something much more different

**Comment by rrhyast** [comment]
my man is bald

**Comment by JannesBonk** [comment]
> my man is bald

me?

**Pull request merged**
