### PR TITLE
Keybinds change (based of watermark)

### PR DESCRIPTION
**Pull request by VegifZyx1336**
Made with help of !SLENDY!#2572
ss:
kyk3bwhhFz

### CODE REVIEW

**Comment by SewqPL** [comment]
omg beste

**Comment by Liam5750** [comment]
I mean.....

**Comment by Xsintashi** [comment]
notgoodusename won't merge that, cuz it doesn't fit with GUI style.

**Comment by VegifZyx1336** [comment]
> notgoodusename won't merge that, cuz it doesn't fit with GUI style.

So does the watermark? and he merged it.

**Comment by SewqPL** [comment]
> notgoodusename won't merge that, cuz it doesn't fit with GUI style.

then change the gui style

**Comment by Xsintashi** [comment]
> > notgoodusename won't merge that, cuz it doesn't fit with GUI style.
> 
> then change the gui style

do it if ur bored

**Comment by VegifZyx1336** [comment]
> notgoodusename won't merge that, cuz it doesn't fit with GUI style.

well look so does the grindys watermark but eh even tho he might not merge it for someone that has the gui style that this fits will use it

**Comment by wirekuro** [comment]
might you do spectator list too?

**Comment by gr1ndy** [comment]
> > Made with help of !SLENDY!#2572
> > ss:
> > kyk3bwhhFz
> 
> goofy ah keybinds

image
image
yikessssssssss

**Pull request closed without merging**
