### PR TITLE
modifiable slowwalk amount

### PR DESCRIPTION
**Pull request by NeurAIGod**
Allow slowwalk speed to be changed, if it's set 0 the old behaviour will be used.

P.S. the text overflows, I personally think the window should be resizable or at least made bigger.

### CODE REVIEW

**Comment by Navoichyk** [comment]
> Allow slowwalk speed to be changed, if it's set 0 the old behaviour will be used.
> 
> P.S. the text overflows, I personally think the window should be resizable or at least made bigger.

I added it and it doesnt seem like it works?

**Comment by Acurisu** [comment]
> I added it and it doesnt seem like it works?

Works for me:
image

**Comment by NeurAIGod** [comment]
Works for me and everyone else I gave it to test:
178114369-387e8f6f-0986-4234-b14a-f9a5c42c7917

**Comment by Navoichyk** [comment]
> Works for me and everyone else I gave it to test: 178114369-387e8f6f-0986-4234-b14a-f9a5c42c7917

yes, i do believe it works, i think i just put it in wrong

**Comment by NeurAIGod** [comment]
> yes, i do believe it works, i think i just put it in wrong

To test PRs like this you shouldn't manually add the code, just pull the fork, checkout the branch and then compile.

**Comment by Navoichyk** [comment]
> > yes, i do believe it works, i think i just put it in wrong
> 
> To test PRs like this you shouldn't manually add the code, just pull the fork, checkout the branch and then compile.

I use cristyanuls fork bc of the dt and hideshots as well as other things. So unless he adds it, i add it

**Comment by Navoichyk** [comment]
i was wrong, it doesn't work. Maybe something with his fork is conflicting with it but idk its just not working. I double checked everything and its exactly the same way you did it. ;(

**Comment by NeurAIGod** [comment]
Can't help much without knowing on which commit/branch you are on the fork because I don't think the latest commit on main compiles.

**Comment by Navoichyk** [comment]
> Can't help much without knowing on which commit/branch you are on the fork because I don't think the latest commit on main compiles.

https://github.com/cristyanul/OsirisAndExtra I use this. The newest one.

**Comment by NeurAIGod** [comment]
You sure you have the latest version? How can it compile with `Glow::drawGUI` at [Glow.cpp#L149](https://github.com/cristyanul/OsirisAndExtra/blob/main/Osiris/Hacks/Glow.cpp#L149) while not having it anywhere in the Glow namespace (see [Glow.h](https://github.com/cristyanul/OsirisAndExtra/blob/main/Osiris/Hacks/Glow.h))?

**Comment by NeurAIGod** [comment]
I just checked out 548ea4c7cde5a44d669a90d1f4593521412c0036 and implemented it there and it worked without issues. Beware the slowwalk is in a different place there but it works so it seems that you are doing something wrong.

**Comment by NeurAIGod** [comment]
@notgoodusename any reasoning that this is not being merged? Asking because the other PRs got accepted.

**Comment by notgoodusename** [comment]
> @notgoodusename any reason that this is not being merged? Asking because the other PRs got accepted and would adapt this one to fit to your liking.

Its fine

**Pull request merged**
