### PR TITLE
Added recoilControlSystem & Update backtrack aimPunch

### PR DESCRIPTION
**Pull request by 2933968621**

### CODE REVIEW

**Comment by 2933968621** [comment]
> What does silent rcs do? Does it mean its enabled when aimbot is silent or is the weapon (animation) not disturbed by recoil control? #confused

yes, weapon animation not disturbed by recoil control
with 'no view punch' and 'no aim punch' is better

**Comment by alerion921** [comment]
Aha cool!

**Comment by 2933968621** [comment]
> > _ No description provided. _
> 
> Hey! I tried using your code but it keeps saying that it is not a member of config::legitbot
> 

but there were no problems with the build check

**Comment by cristyanul** [comment]
It works, but it's bad.
First: Vertical and horizontal are vice-versa 🤦 
Secondly:
If setting both to 1 I expect the bullets to be as close to a laser beam as possible. In this case if you set both to 1 they go crazy overpowering the recoil way to much and creating reverse recoil on the pitch axis.

**Comment by 2933968621** [comment]
> It works, but it's bad. First: Vertical and horizontal are vice-versa 🤦 Secondly: If setting both to 1 I expect the bullets to be as close to a laser beam as possible. In this case if you set both to 1 they go crazy overpowering the recoil way to much and creating reverse recoil on the pitch axis.

Thanks for your advice. I will check these problems tomorrow < 3

**Comment by 2933968621** [comment]
> It works, but it's bad. First: Vertical and horizontal are vice-versa 🤦 Secondly: If setting both to 1 I expect the bullets to be as close to a laser beam as possible. In this case if you set both to 1 they go crazy overpowering the recoil way to much and creating reverse recoil on the pitch axis.

Well, the problem has been solved

**Pull request merged**
