### PR TITLE
Draw Hitboxes On Hit

### PR DESCRIPTION
**Pull request by Xsintashi**
Provided by yours truly at 3 am.

Tried to make that working with Backtrack records, but gave up and made that on event listener. If u wanna change that, then make pr.

Closes this I guess: https://github.com/notgoodusename/OsirisAndExtra/projects/1#card-74467627

https://user-images.githubusercontent.com/61426269/214464415-59f5e63e-46ed-4d60-93be-12bfaef288c6.mp4

### CODE REVIEW

**Comment by gr1ndy** [comment]
it might be me, but it looks like youre drawing the last tick after you shot.

**Comment by Xsintashi** [comment]
> yo @Xsintashi gimme the code for the bt one, ill fix it for u

i dont have it, but it worked something like. if ragebot shot then just instead `Entity* entity` in arguments, u had `Animations::Records* record`

**Comment by Xsintashi** [comment]
> > > yo @Xsintashi gimme the code for the bt one, ill fix it for u
> > 
> > i dont have it, but it worked something like. if ragebot shot then just instead `Entity* entity` in arguments, u had `Animations::Records* record`
> 
> have u tried maybe using snapshots? just like the resolver, if miss due to bt then show miss, but in our case is, if bt hit then show at bt tick

I will look into it.

**Comment by Xsintashi** [comment]
https://user-images.githubusercontent.com/61426269/214831632-c70dc946-1fa2-4662-9424-47e936ab2e9b.mp4

for backtracking works

**Comment by Xsintashi** [comment]
> > 8mb.video-7kY-uotx56X3.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > for backtracking works
> 
> its either that u fixed rn, or is just smth else, played hvh with it yesterday and it showed only where the player was even tho i was shooting at backtrack.

i know cuz its based on events, so matrix appears where enemy was on last tick

**Comment by Xsintashi** [comment]
> > > > 8mb.video-7kY-uotx56X3.mp4
> > > > for backtracking works
> > > 
> > > 
> > > its either that u fixed rn, or is just smth else, played hvh with it yesterday and it showed only where the player was even tho i was shooting at backtrack.
> > 
> > 
> > fixed and i know cuz its based on events, so matrix appeared where enemy was on last tick
> 
> now we wait for push

at this moment only with ragebot, so let me only do it also for normal backtracking

**Comment by Xsintashi** [comment]
> > > > 8mb.video-7kY-uotx56X3.mp4
> > > > for backtracking works
> > > 
> > > 
> > > its either that u fixed rn, or is just smth else, played hvh with it yesterday and it showed only where the player was even tho i was shooting at backtrack.
> > 
> > 
> > fixed and i know cuz its based on events, so matrix appeared where enemy was on last tick
> 
> now we wait for push

If u want it faster:
image
Its for ragebot only

**Comment by Xsintashi** [comment]
nah it doesnt

**Comment by Xsintashi** [comment]
> > nah it doesnt
> 
> how tf did we get the same code 💀

idk but issue is, it only takes matrix for backtrack, even if u didnt hit at records

**Comment by Xsintashi** [comment]
https://user-images.githubusercontent.com/61426269/214871104-b579c1dd-cf6c-4d9e-9b81-49553aae70f3.mp4

Sometimes matrix may appear higher than it should. Its capsuleOverlay function issue, not mine.

**Comment by dapaster** [comment]
+1

**Comment by deathruned** [comment]
share the commands that you used for showcase.

**Comment by Xsintashi** [comment]
> share the commands that you used for showcase.

weapon_recoil_scale 0;weapon_accuracy_nospread 1;sv_infinite_ammo 1

**Review by xomarko — APPROVED** [review]

**Comment by MesuDevastator** [comment]
Weird problem while turned fake lag and backtrack on with this simultaneously

https://user-images.githubusercontent.com/50985752/215317040-51d519fa-6323-4655-af78-19b6ff7b164c.mp4

**Comment by Xsintashi** [comment]
> > Weird problem while turned fake lag and backtrack on with this simultaneously
> > (h265 encoded video, pls download to watch, otherwise you can only hear sound
> > 
> >   
> >     
> >     
> > 
> >     video.mp4
> 
> cheat issue idk

bro, u have 10 fps and lagged server, that's why u miss most likely. Also probably bots animations are broken

**Comment by MesuDevastator** [comment]
I might recorded poorly :(
That floating bot is not the point...
The biggest problem is that while turning fake lag and backtrack on with this, the drawn hitbox is incorrectly at where the latest backtrack record is (sorry to my poor English

**Comment by Xsintashi** [comment]
Hitboxes are supposted to draw at hit record, not at last recorded

https://user-images.githubusercontent.com/61426269/215326553-ed9e2c5f-6d31-426f-b171-ce377b1e701e.mp4

**Comment by JukoiDev** [comment]
looks good to me

**Pull request merged**
