### PR TITLE
Tickbase Manipulation (Doubletap)

### PR DESCRIPTION
**Pull request by dapaster**
https://user-images.githubusercontent.com/60472098/179024221-13fa6149-1d97-43d0-ae1d-8d529c09f1e7.mp4

### CODE REVIEW

**Comment by Navoichyk** [comment]
hey @dapaster, i tried adding your code, but its just saying this at the end, "
1>Hooks.obj : error LNK2001: unresolved external symbol "void __vectorcall Tickbase::run(struct UserCmd *)" (?run@Tickbase@@YQXPAUUserCmd@@@Z)
1>C:\Users\Roman\Desktop\OsirisAndExtra-main\Release\Osiris.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "Osiris.vcxproj" -- FAILED."

**Comment by Navoichyk** [comment]
You should definitely fix this!

**Comment by dapaster** [comment]
@Navoichyk 
@notgoodusename

how to add file _Tickbase.cpp_ & _Tickbase.h_ into `Osiris/Hacks/` ?

I create the file but when compiling the file is not exist at this directory `Osiris/Hacks/Tickbase.cpp`

the file *Tickbase.cpp* & *Tickbase.h* is not appear at `Osiris/Hacks/`

**Comment by Navoichyk** [comment]
> @Navoichyk @notgoodusename
> 
> how to add file _Tickbase.cpp_ & _Tickbase.h_ into `Osiris/Hacks/` ?
> 
> I create the file but when compiling the file is not exist at this directory `Osiris/Hacks/Tickbase.cpp`
> 
> the file _Tickbase.cpp_ & _Tickbase.h_ is not appear at `Osiris/Hacks/`

You have to include it correctly I think? Also there an issue with memory

**Pull request closed without merging**
