### PR TITLE
Unhide Convars is toggable

### PR DESCRIPTION
**Pull request by Xsintashi**
https://user-images.githubusercontent.com/61426269/204663401-eb722ab7-41be-44e8-b136-c031e2456071.mp4

### CODE REVIEW

**Comment by Navoichyk** [comment]
how tf did u get the background and diff player on the loading screen

**Comment by Xsintashi** [comment]
> how tf did u get the background and diff player on the loading screen

1. Background is made by myself but u can use other custom backgrounds [here](https://csgo.red).
2. This is legit agent skin on my acc.

**Comment by Navoichyk** [comment]
> > how tf did u get the background and diff player on the loading screen
> 
> 1. Background is made by myself but u can use other custom backgrounds [here](https://csgo.red).
> 2. This is legit agent skin on my acc.

i deadass thought u just added a feature into the cheat to do it lmfao

**Comment by Xsintashi** [comment]
> > > how tf did u get the background and diff player on the loading screen
> > 
> > 
> > 
> > 1. Background is made by myself but u can use other custom backgrounds [here](https://csgo.red).
> > 2. This is legit agent skin on my acc.
> 
> i deadass thought u just added a feature into the cheat to do it lmfao

tbh i was thinking about hooking panorama engine and modify overall cs:go interface. too much shit with it

**Pull request merged**
