### PR TITLE
Attachment chams

### PR DESCRIPTION
**Pull request by JannesBonk**
Adds attachment chams when having weapon chams activated

### CODE REVIEW

**Comment by rrhyast** [comment]
+c4, defuse kit, utilities?

**Comment by rrhyast** [comment]
> > +c4, defuse kit, utilities?
> 
> everything that has a _w in the game files will show

@notgoodusename time to  pushin p

**Comment by rrhyast** [comment]
> > +C4, Defuse kit, Utilities?
> 
> image

this is my favorite pull request

**Comment by notgoodusename** [comment]
Does it work on grenades?

**Comment by notgoodusename** [comment]
Ok, I'm gonna fuse this, just beware that grenades won't be rendered with chams

**Pull request merged**
