### PR TITLE
Add hurt indicator

### PR DESCRIPTION
**Pull request by worse-666**
image

### CODE REVIEW

**Comment by cristyanul** [comment]
> 

which pull?

**Comment by cristyanul** [comment]
I get crashes the second time i connect in a match

**Comment by Rrhyast** [comment]
> > 
> 
> which pull?

After commits on May 22, 2022

**Comment by alerion921** [comment]
I believe its in the hurt indicator pull where misc where the function was added 😂😂

**Comment by Rrhyast** [comment]
> > > > 
> > > 
> > > 
> > > which pull?
> > 
> > 
> > After commits on May 29, 2022
> 
> #146 This?

yes

**Comment by worse-666** [comment]
> > > > > 
> > > > 
> > > > 
> > > > which pull?
> > > 
> > > 
> > > After commits on May 29, 2022
> > 
> > 
> > #146 This?
> 
> yes

Sorry I've been testing for a long time and it didn't crash, so I don't know what's wrong

**Comment by rrhyast** [comment]
Why this doesn't merge

**Pull request merged**
