### PR TITLE
Add Aimbot Fov

### PR DESCRIPTION
**Pull request by Navoichyk**
I think aimbot fov would be really nice, as well as useful.

### CODE REVIEW

**Comment by JukoiDev** [comment]
tickbase? autopeek? are you sure you didnt select the wrong thing?

**Comment by Navoichyk** [comment]
I did choose the wrong thing. I don’t really know how to use pr so I just did this. But I’m just requesting aimbot fov.

**Comment by notgoodusename** [comment]
> I did choose the wrong thing. I don’t really know how to use pr so I just did this. But I’m just requesting aimbot fov.

just create an issue

**Comment by Navoichyk** [comment]
> > I did choose the wrong thing. I don’t really know how to use pr so I just did this. But I’m just requesting aimbot fov.
> 
> just create an issue

I did.

**Pull request closed without merging**
